services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  app:
    build:
      dockerfile: ./Dockerfile
    command: >
      sh -c "python manage.py migrate &&
             gunicorn crm_system.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - static_data:/app/staticfiles
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_data:/usr/share/nginx/html/static
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  postgres_data:
  static_data: