# Generated by Django 5.1.3 on 2024-11-20 01:32

import clients.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advertising', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PotentialClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=50)),
                ('last_name', models.CharField(db_index=True, max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=20, validators=[clients.models.validate_phone_number])),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('advertising_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potential_clients', to='advertising.advertisingcompany')),
            ],
        ),
    ]
