# Generated by Django 5.1.3 on 2024-11-20 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potentialclient',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
    ]
