# Generated by Django 5.1.3 on 2024-11-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0001_initial'),
        ('clients', '0002_alter_potentialclient_email'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='potentialclient',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name', 'middle_name', 'phone_number', 'email', 'advertising_company'), name='unique_field_combination'),
        ),
    ]
