# Generated by Django 5.1.3 on 2024-11-20 07:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_potentialclient_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='potentialclient',
            name='next_interaction_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
