# Generated by Django 5.1.3 on 2024-11-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_potentialclient_next_interaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='potentialclient',
            name='is_active',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
