# Generated by Django 5.1.3 on 2024-11-21 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0001_initial'),
        ('clients', '0007_potentialclient_is_active'),
        ('contracts', '0002_alter_contract_documentation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PotentialClient',
            new_name='Client',
        ),
    ]
