# Generated by Django 5.1.3 on 2024-11-21 02:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_rename_potentialclient_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['next_interaction_date']},
        ),
        migrations.AlterField(
            model_name='client',
            name='next_interaction_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
