# Generated by Django 5.1.3 on 2024-11-20 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='documentation',
            field=models.FileField(null=True, upload_to='contracts/documentations/'),
        ),
    ]
