# Generated by Django 5.1.3 on 2024-11-21 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_rename_potentialclient_client'),
        ('contracts', '0002_alter_contract_documentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='active_client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
            preserve_default=False,
        ),
    ]
