# Generated by Django 5.1.3 on 2024-11-21 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contract_active_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='active_client',
            new_name='client',
        ),
    ]
