# Generated by Django 5.1.3 on 2024-11-21 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_rename_potentialclient_client'),
        ('contracts', '0004_rename_active_client_contract_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='clients.client'),
        ),
    ]
