# Generated by Django 5.1.3 on 2024-11-21 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_alter_contract_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['start_date', 'pk']},
        ),
    ]
