# Generated by Django 5.1.3 on 2024-11-21 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_alter_client_options_and_more'),
        ('contracts', '0007_alter_contract_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='clients.client'),
        ),
    ]
