# Generated by Django 5.1.3 on 2024-11-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_alter_contract_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='documentation',
            field=models.FileField(blank=True, default='/home/themswesson/Desktop/test/mypdf.pdf', null=True, upload_to='contracts/documentations/'),
        ),
    ]
