# Generated by Django 5.1.3 on 2024-11-18 07:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0003_alter_service_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisingCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, unique=True)),
                ('promotion_channel', models.CharField(db_index=True, max_length=100)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0, 'The price cannot be below zero')])),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertising_companies', to='services.service')),
            ],
        ),
    ]
